/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ApplicationSuccessRouteImport } from './routes/application-success'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UpskillIdRouteImport } from './routes/upskill.$id'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as AssessmentsIdRouteImport } from './routes/assessments.$id'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as JobsIdApplyRouteImport } from './routes/jobs.$id_.apply'
import { Route as AdminJobsNewRouteImport } from './routes/admin.jobs.new'
import { Route as AdminJobsIdEditRouteImport } from './routes/admin.jobs.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationSuccessRoute = ApplicationSuccessRouteImport.update({
  id: '/application-success',
  path: '/application-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpskillIdRoute = UpskillIdRouteImport.update({
  id: '/upskill/$id',
  path: '/upskill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIdRoute = AssessmentsIdRouteImport.update({
  id: '/assessments/$id',
  path: '/assessments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdApplyRoute = JobsIdApplyRouteImport.update({
  id: '/jobs/$id_/apply',
  path: '/jobs/$id/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsNewRoute = AdminJobsNewRouteImport.update({
  id: '/admin/jobs/new',
  path: '/admin/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIdEditRoute = AdminJobsIdEditRouteImport.update({
  id: '/admin/jobs/$id/edit',
  path: '/admin/jobs/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/application-success': typeof ApplicationSuccessRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/choose-role': typeof ChooseRoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/upskill/$id': typeof UpskillIdRoute
  '/admin/': typeof AdminIndexRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin/jobs/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/application-success': typeof ApplicationSuccessRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/choose-role': typeof ChooseRoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/upskill/$id': typeof UpskillIdRoute
  '/admin': typeof AdminIndexRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin/jobs/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/application-success': typeof ApplicationSuccessRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/choose-role': typeof ChooseRoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/upskill/$id': typeof UpskillIdRoute
  '/admin/': typeof AdminIndexRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/jobs/$id_/apply': typeof JobsIdApplyRoute
  '/admin/jobs/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/application-success'
    | '/applications'
    | '/apply'
    | '/choose-role'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/profile'
    | '/assessments/$id'
    | '/jobs/$id'
    | '/messages/$id'
    | '/upskill/$id'
    | '/admin/'
    | '/assessments/'
    | '/jobs/'
    | '/messages/'
    | '/admin/jobs/new'
    | '/jobs/$id/apply'
    | '/admin/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/application-success'
    | '/applications'
    | '/apply'
    | '/choose-role'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/profile'
    | '/assessments/$id'
    | '/jobs/$id'
    | '/messages/$id'
    | '/upskill/$id'
    | '/admin'
    | '/assessments'
    | '/jobs'
    | '/messages'
    | '/admin/jobs/new'
    | '/jobs/$id/apply'
    | '/admin/jobs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/application-success'
    | '/applications'
    | '/apply'
    | '/choose-role'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/profile'
    | '/assessments/$id'
    | '/jobs/$id'
    | '/messages/$id'
    | '/upskill/$id'
    | '/admin/'
    | '/assessments/'
    | '/jobs/'
    | '/messages/'
    | '/admin/jobs/new'
    | '/jobs/$id_/apply'
    | '/admin/jobs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApplicationSuccessRoute: typeof ApplicationSuccessRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ApplyRoute: typeof ApplyRoute
  ChooseRoleRoute: typeof ChooseRoleRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AssessmentsIdRoute: typeof AssessmentsIdRoute
  JobsIdRoute: typeof JobsIdRoute
  MessagesIdRoute: typeof MessagesIdRoute
  UpskillIdRoute: typeof UpskillIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  AdminJobsNewRoute: typeof AdminJobsNewRoute
  JobsIdApplyRoute: typeof JobsIdApplyRoute
  AdminJobsIdEditRoute: typeof AdminJobsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-success': {
      id: '/application-success'
      path: '/application-success'
      fullPath: '/application-success'
      preLoaderRoute: typeof ApplicationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upskill/$id': {
      id: '/upskill/$id'
      path: '/upskill/$id'
      fullPath: '/upskill/$id'
      preLoaderRoute: typeof UpskillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$id': {
      id: '/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AssessmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id_/apply': {
      id: '/jobs/$id_/apply'
      path: '/jobs/$id/apply'
      fullPath: '/jobs/$id/apply'
      preLoaderRoute: typeof JobsIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/new': {
      id: '/admin/jobs/new'
      path: '/admin/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AdminJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/$id/edit': {
      id: '/admin/jobs/$id/edit'
      path: '/admin/jobs/$id/edit'
      fullPath: '/admin/jobs/$id/edit'
      preLoaderRoute: typeof AdminJobsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApplicationSuccessRoute: ApplicationSuccessRoute,
  ApplicationsRoute: ApplicationsRoute,
  ApplyRoute: ApplyRoute,
  ChooseRoleRoute: ChooseRoleRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AssessmentsIdRoute: AssessmentsIdRoute,
  JobsIdRoute: JobsIdRoute,
  MessagesIdRoute: MessagesIdRoute,
  UpskillIdRoute: UpskillIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  AdminJobsNewRoute: AdminJobsNewRoute,
  JobsIdApplyRoute: JobsIdApplyRoute,
  AdminJobsIdEditRoute: AdminJobsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
