/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ApplicationSuccessRouteImport } from './routes/application-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as JobsIdApplyRouteImport } from './routes/jobs.$id.apply'
import { Route as AdminJobsNewRouteImport } from './routes/admin.jobs.new'
import { Route as AdminJobsIdEditRouteImport } from './routes/admin.jobs.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationSuccessRoute = ApplicationSuccessRouteImport.update({
  id: '/application-success',
  path: '/application-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdApplyRoute = JobsIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsIdRoute,
} as any)
const AdminJobsNewRoute = AdminJobsNewRouteImport.update({
  id: '/admin/jobs/new',
  path: '/admin/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIdEditRoute = AdminJobsIdEditRouteImport.update({
  id: '/admin/jobs/$id/edit',
  path: '/admin/jobs/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application-success': typeof ApplicationSuccessRoute
  '/applications': typeof ApplicationsRoute
  '/choose-role': typeof ChooseRoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin/jobs/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-success': typeof ApplicationSuccessRoute
  '/applications': typeof ApplicationsRoute
  '/choose-role': typeof ChooseRoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin/jobs/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/application-success': typeof ApplicationSuccessRoute
  '/applications': typeof ApplicationsRoute
  '/choose-role': typeof ChooseRoleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin/jobs/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application-success'
    | '/applications'
    | '/choose-role'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/applications'
    | '/jobs/$id'
    | '/admin/'
    | '/jobs/'
    | '/admin/jobs/new'
    | '/jobs/$id/apply'
    | '/admin/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-success'
    | '/applications'
    | '/choose-role'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/applications'
    | '/jobs/$id'
    | '/admin'
    | '/jobs'
    | '/admin/jobs/new'
    | '/jobs/$id/apply'
    | '/admin/jobs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/application-success'
    | '/applications'
    | '/choose-role'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/applications'
    | '/jobs/$id'
    | '/admin/'
    | '/jobs/'
    | '/admin/jobs/new'
    | '/jobs/$id/apply'
    | '/admin/jobs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationSuccessRoute: typeof ApplicationSuccessRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ChooseRoleRoute: typeof ChooseRoleRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  JobsIdRoute: typeof JobsIdRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  AdminJobsNewRoute: typeof AdminJobsNewRoute
  AdminJobsIdEditRoute: typeof AdminJobsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-success': {
      id: '/application-success'
      path: '/application-success'
      fullPath: '/application-success'
      preLoaderRoute: typeof ApplicationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id/apply': {
      id: '/jobs/$id/apply'
      path: '/apply'
      fullPath: '/jobs/$id/apply'
      preLoaderRoute: typeof JobsIdApplyRouteImport
      parentRoute: typeof JobsIdRoute
    }
    '/admin/jobs/new': {
      id: '/admin/jobs/new'
      path: '/admin/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AdminJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/$id/edit': {
      id: '/admin/jobs/$id/edit'
      path: '/admin/jobs/$id/edit'
      fullPath: '/admin/jobs/$id/edit'
      preLoaderRoute: typeof AdminJobsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsIdRouteChildren {
  JobsIdApplyRoute: typeof JobsIdApplyRoute
}

const JobsIdRouteChildren: JobsIdRouteChildren = {
  JobsIdApplyRoute: JobsIdApplyRoute,
}

const JobsIdRouteWithChildren =
  JobsIdRoute._addFileChildren(JobsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationSuccessRoute: ApplicationSuccessRoute,
  ApplicationsRoute: ApplicationsRoute,
  ChooseRoleRoute: ChooseRoleRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  JobsIdRoute: JobsIdRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  AdminJobsNewRoute: AdminJobsNewRoute,
  AdminJobsIdEditRoute: AdminJobsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
